# ── algo/model.py ────────────────────────────────────────────────
"""
3‑class (‑1 / 0 / +1) XGBoost model for intraday ML signals.

• Data **must** already contain technical indicators and a `label`
  column with values ‑1, 0, +1 (generated by add_labels()).

Exports
-------
load_or_train(df, retrain=False)  → fitted model
predict_last_vec(df_window, model)→ (p_long, p_short) tuple
predict_last(df_window, model)    → p_long only (kept for legacy code)
"""

import time
import pathlib
import joblib
import numpy as np
import pandas as pd

from numpy.lib.stride_tricks import sliding_window_view
from xgboost                  import XGBClassifier
from sklearn.pipeline         import Pipeline
from sklearn.impute           import SimpleImputer
from sklearn.model_selection  import train_test_split
from sklearn.metrics          import accuracy_score, log_loss

from algo.features            import FEATURES

# ── shared constants (keep in sync with features.py & backtester.py) ──
LOOKBACK   = 60     # bars fed into the model
HORIZON    = 24     # label / time‑stop horizon (bars)
_MODELFILE = pathlib.Path(__file__).with_suffix(".pkl")

# ─────────────────────────────────────────────────────────────────
def _make_sliding_X(df: pd.DataFrame) -> np.ndarray:
    """
    Build an (N‑LOOKBACK+1, LOOKBACK*len(FEATURES)) design matrix
    with a memory‑efficient window slide along the time axis only.
    """
    arr  = df[FEATURES].to_numpy("float64")            # shape (N, F)
    view = sliding_window_view(arr, LOOKBACK, axis=0)  # (N‑L+1, L, F)
    return view.reshape(view.shape[0], -1)             # flatten last 2 axes


def _prepare_xy(df: pd.DataFrame, horizon: int = HORIZON):
    """
    Return X, y pairs for 3‑class classification.
    Assumes `label` column contains −1 / 0 / +1.
    """
    df = df.copy()
    df.dropna(subset=FEATURES + ["label"], inplace=True)

    X_all = _make_sliding_X(df)[:-horizon]                         # align
    y_all = df["label"].iloc[LOOKBACK - 1 : -horizon].to_numpy()

    # map label −1→0, 0→1, +1→2
    y_all = (y_all + 1).astype("int8")

    assert X_all.shape[0] == len(y_all), "X/y length mismatch"

    mask = np.isfinite(X_all).all(axis=1)           # drop rows with NaNs
    print(
        f"Prepared {mask.sum()} samples | Class counts:",
        {c: int((y_all[mask] == c).sum()) for c in range(3)},
    )
    return X_all[mask], y_all[mask]


def _build_pipe() -> Pipeline:
    """
    XGBoost wrapped in a scikit‑learn Pipeline with imputation.
    """
    xgb_params = dict(
        n_estimators     = 700,
        learning_rate    = 0.03,
        max_depth        = 6,
        subsample        = 0.9,
        colsample_bytree = 0.8,
        gamma            = 0.2,
        reg_lambda       = 1.0,
        objective        = "multi:softprob",    # 3‑class
        num_class        = 3,
        eval_metric      = "mlogloss",
        n_jobs           = -1,
        random_state     = 0,
    )
    return Pipeline(
        [
            ("imp", SimpleImputer(strategy="mean")),
            ("xgb", XGBClassifier(**xgb_params)),
        ]
    )


# ─────────────────────────────────────────────────────────────────
def load_or_train(
    df: pd.DataFrame,
    *,
    retrain: bool = False,
    horizon: int = HORIZON,
):
    """
    Train a new model on `df` or load the cached one.
    The DataFrame must already include indicators and 3‑class labels.
    """
    if _MODELFILE.exists() and not retrain:
        print("ℹ️  Loading cached model …")
        return joblib.load(_MODELFILE)

    # ─ Training ─
    X, y = _prepare_xy(df, horizon)
    Xtr, Xval, ytr, yval = train_test_split(
        X, y, test_size=0.20, shuffle=False
    )

    pipe = _build_pipe()
    print("🔧  Training …"); t0 = time.time()
    pipe.fit(
        Xtr,
        ytr,
        xgb__eval_set=[(Xval, yval)],
        xgb__verbose=False,
    )
    dur = time.time() - t0
    pval = pipe.predict_proba(Xval)
    print(
        f"✅  Finished in {dur:.1f}s | val‑logloss {log_loss(yval, pval):.4f}"
        f" | acc {accuracy_score(yval, pipe.predict(Xval)):.3f}"
    )

    joblib.dump(pipe, _MODELFILE)
    return pipe


# ── helpers for back‑tester ──────────────────────────────────────
def _window_to_X(df_window: pd.DataFrame, lookback: int) -> np.ndarray | None:
    """Shared conversion utility; returns 1×(lookback*F) or None on NaN."""
    if len(df_window) < lookback:
        return None
    X = (
        df_window[FEATURES]
        .iloc[-lookback:]
        .to_numpy("float64")
        .flatten()
        .reshape(1, -1)
    )
    if np.isnan(X).any():
        return None
    return X


def predict_last_vec(
    df_window: pd.DataFrame,
    model,
    *,
    lookback: int = LOOKBACK,
) -> tuple[float, float]:
    """
    Return (p_long, p_short) = (P[class = +1], P[class = ‑1]).
    If data insufficient ⇒ (np.nan, np.nan).
    """
    X = _window_to_X(df_window, lookback)
    if X is None:
        return np.nan, np.nan

    proba = model.predict_proba(X)[0]  # shape (3,)
    return float(proba[2]), float(proba[0])   # (+1, ‑1)


# Legacy helper (still ok for binary workflows)
def predict_last(
    df_window: pd.DataFrame,
    model,
    *,
    lookback: int = LOOKBACK,
) -> float:
    """
    Return **probability of the long class** (class index 2).
    Kept for compatibility with older binary scripts.
    """
    X = _window_to_X(df_window, lookback)
    if X is None:
        return np.nan
    return float(model.predict_proba(X)[0][2])
